### ISSUE TITLE
Autocomplete and type hint using Coc.

### ISSUE THREAD

**Issue by bergsans** [stefanvanburen/rams#6]
Hello! Thank you very much for sharing your Rams-inspired colorscheme - very elegant!

Floating windows from autocomplete and type hint (possibly others) used by [Coc](https://github.com/neoclide/coc.nvim) uses the same background and foreground color as the rest of the document. Especially type hints are hard to see.

I am not sure if this is design decision, or missing support for a package (perhaps Coc) or if it is my environment and NeoVim-config.

In my init.vim I link Coc-menu-ish things to Pmenu:

```
hi! link WildMenu Pmenu
hi! link CocMenuSel PmenuSel
hi! link CocHintFloat Pmenu
hi! link CocInfoFloat Pmenu
hi! link CocPumMenu Pmenu
hi! link CocInlayHint Pmenu
hi! link CocPumVirtualText Comment
```

If you need more information, I will try to provide it.

Example with type hint for `ASTNode`. In my settings I use `K` in normal mode.
![Screenshot from 2022-11-29 08-08-23](https://user-images.githubusercontent.com/66532014/204463586-447cda30-8084-4541-b0b6-fc7b9a9b2556.png)

Example with auto-complete `conso` from insert mode.
![Screenshot from 2022-11-29 08-09-19](https://user-images.githubusercontent.com/66532014/204463592-5e4ffe40-11eb-40a2-9383-22c326d4c32e.png)

Again, I love this colortheme! So simple, yet elegant and beautiful!

**Comment by stefanvanburen** [comment]
hey @bergsans, thanks for the kind words!

After seeing your examples, I think I understand a bit better, and I'd say it's ... somewhat by design; at least for _some_ popups, I've been setting `border = single` to differentiate the popup from the rest of the document:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/622527/204674196-b05d4c0d-c005-4923-ae63-67bf7256e5af.png">

However, I realize that doesn't work that well for all popups / menus. For example, when opening completion with omnifunc, it's really not differentiated from the rest of the UI:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/622527/204674378-da297592-a5ce-41ad-9243-3dee69585282.png">

Hmm, I'll have to think about this!

**Comment by bergsans** [comment]
How about inverting the colors in all popus? Or do you think that would break with the rest of the design?

**Comment by stefanvanburen** [comment]
In https://github.com/stefanvanburen/rams/commit/2ee1582b3e9485a78b5835bac21fa4eec5d3b457 I tweaked the settings a little bit - now the popup menu has a light grey background with the currently selected row having a white background, which I like a bit better:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/622527/204804930-5ae40332-f54a-4327-83d5-f7e49e3d2dae.png">

In general I try to avoid using the black as a background because it feels heavy IMO. I'm still undecided, though - feel free to pull it down and try it out!

**Comment by bergsans** [comment]
Looks great on your image, thanks! However, its seems to depend on lua now? I cannot run the latest version. But that's on me, I am a dinosaur, I should change to using lua for NeoVim config. :)

**Comment by stefanvanburen** [comment]
No worries! I don't think it should depend on lua as long as you're using neovim. What's the error you're seeing?

**Comment by stefanvanburen** [comment]
ahh, I see. I think currently, `rams` requires [lush.nvim](https://github.com/rktjmp/lush.nvim) to also be installed to work. It looks like other colorschemes made with lush will sometimes have a "compatibility mode" to set colors without lush.nvim being installed (see https://github.com/mcchrish/zenbones.nvim/blob/main/colors/zenwritten.vim#L7-L10 - also another great colorscheme!).

I probably won't get around to adding that for awhile as I typically just leave lush.nvim installed for development, so probably your best bet is to install lush.nvim as well for now, sorry 😄.

**Comment by bergsans** [comment]
Will try! And again, an elegant colorscheme! Well done!
